### ISSUE TITLE
Default Fire Starter

### ISSUE THREAD

**Issue by x33st0rm** [WulfMarius/Binoculars#2]
Whenever i try to start a fire, the binocular is the first item selected as a starter by default.
It's not something i want to use as my first choice, but rather my last.

Is there something that can be done about this, like making an alternate? Like renaming it Z-Lite Binoculars or something?

I'm not sufficient enough to make the changes though..

Thanks for all your work btw.

**Comment by WulfMarius** [comment]
I checked to see what's happening and the firestarters are simply sorted by name.
That always moves the Binoculars to the first position.

Adjusting the way they are sorted is not too difficult, but I don't know what the proper order would be. And then there's the question where this change should go (currently tending to ModComponent).

However I agree that the order is not very helpful or intuitive and will address this one way or another.
Thanks for letting me know.

**Comment by x33st0rm** [comment]
Alphabetical Sorting i guess, but with the displayed name or an internal one i wonder.
The magnifying glass is always first selection, after the binoculars, and oh so rare that the sun is actually out in this game. I just went with no having either the binocs or mag glass in my walking around kit.

Would actually be awesome to have a light sorting mod, to make default selections better.
A weight sorting, so the default and first selections are the ones weighing you down the most.

Awesome you're gonna look into it, i'll be looking forward to see what you come up with :)

**Comment by WulfMarius** [comment]
I decided to make a separate mod: https://github.com/WulfMarius/Sort-Fire-Starters
It's very small and probably makes sense even without binoculars.

It's available in Mod-Installer, of course.
HTH

**Comment by x33st0rm** [comment]
That's really awesome man, will be extremely handy! Thanks so much!
